### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by BotTheLostOne** [denoflionsx/HuntControl#4]
is there anyway to enable this on a dedicated server

**Comment by timizorzom** [comment]
bump

**Comment by denoflionsx** [comment]
It works like any other mod. You install it and it works. There are no specific instructions required for a dedicated server.

Mind that the mod was designed for single player so chances are most of the features won't work consistently on dedi. If a throne is unloaded because no player is anywhere near it missions cannot be progressed by the mod.
